#!/bin/sh 
### BEGIN INIT INFO
# Provides:          tomcat
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: The tomcat Java Application Server
### END INIT INFO
#
# description: Auto-starts tomcat
# processname: tomcat

export JAVA_HOME=/usr/lib/jvm/jdk1.8.0_77

case $1 in
start)
sh /opt/apache-tomcat-9.0.0.M6/bin/startup.sh
;;
stop) 
sh /opt/apache-tomcat-9.0.0.M6/bin/shutdown.sh
;;
restart)
sh /opt/apache-tomcat-9.0.0.M6/bin/shutdown.sh
sh /opt/apache-tomcat-9.0.0.M6/bin/startup.sh
;;
esac 
exit 0
